version: '2'

services:
  apache-cassandra:
    image: bingoarun/cassandra:3.10
    build: .
    ports:
    - "4040:4040"
    - "61621:61621"
    - "7077:7077"
    - "7080:7080"
    - "7081:7081"
    - "7199:7199"
    - "9042:9042"
    - "9160:9160"
    volumes: # Update VOLUME in Dockerfile
    - ./tmp1:/var/lib/cassandra
    - ./tmp2:/var/lib/cassandra2
    environment:
      - CASSANDRA_CLUSTER_NAME='Arun test DB'
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_DATA_FILE_DIRECTORIES=[/var/lib/cassandra/,/var/lib/cassandra2/]
      - CASSANDRA_RACK=test_sim_rack
      
      
